### ISSUE TITLE
Batch process for the login and register user

### ISSUE THREAD

**Issue by jmoguilevsky** [decentraland/matrix-load-testing-tool#6]
Right now all users are being registered at the same time, making the server time out during this stage.

The register and log in stage should be made before sending the messages and probably don't need to be part of the overall metrics of the running stage.

Doing the log in and register in batches will allow the test to be more reliable preventing time outs in the warm up, plus it's more realistic to have a lot of users talking at the same time but not necessarily the have logged in at the same time (having a spike of 200 log ins in the same 2 seconds timespan is not very realistic)

**Comment by guidota** [comment]
Solved in #9
